
-- AVALIAÇÃO
-- 1
ALTER TABLE PROFESSOR ADD TOTAL_ALUNOS NUMBER(3);
COMMIT;

-- 2
CREATE OR REPLACE FUNCTION SF_TOTAL_ALUNO_PROF(P_ID_PROFESSOR NUMBER) RETURN NUMBER AS
V_CONT_ALUNOS NUMBER;
BEGIN
    SELECT COUNT(ID_ALUNO)
        INTO V_CONT_ALUNOS
        FROM DISCIPLINA D, ALUNO_DISCIPLINA AD
        WHERE D.ID_PROFESSOR = P_ID_PROFESSOR AND AD.ID_DISCIPLINA = D.ID_DISCIPLINA;
    RETURN V_CONT_ALUNOS;
END;

-- EX 3
DECLARE
V_CONT_ALUNOS NUMBER;
BEGIN 
    FOR PROF_ID IN 1 .. 5 LOOP 
        V_CONT_ALUNOS := SF_TOTAL_ALUNO_PROF(PROF_ID);
        UPDATE PROFESSOR SET TOTAL_ALUNOS = V_CONT_ALUNOS WHERE ID_PROFESSOR = PROF_ID;
    END LOOP;
    COMMIT;
END;

-- EX 4
DECLARE
V_TOT_CIDADES NUMBER;
V_TOT_PROF NUMBER; 
V_ID_CIDADE PROFESSOR.ID_CIDADE%TYPE;
BEGIN
    SELECT ID_CIDADE 
        INTO V_ID_CIDADE FROM PROFESSOR
        WHERE ID_PROFESSOR = 1;
    UPDATE PROFESSOR SET ID_CIDADE = V_ID_CIDADE WHERE ID_PROFESSOR = 2;
END;

-- EX 5 
CREATE OR REPLACE PROCEDURE SP_MOSTRA_DADOS_CIDADE(P_ID_CIDADE NUMBER) AS
V_NOME_CIDADE  CIDADE.NOME_CIDADE%TYPE;
V_TOT_PROF NUMBER;
V_AVG_ALUNO NUMBER;
V_TOT_ALUNO NUMBER;
BEGIN
    SELECT C.NOME_CIDADE 
        INTO V_NOME_CIDADE FROM CIDADE C
        WHERE C.ID_CIDADE = P_ID_CIDADE;
    SELECT COUNT(ID_PROFESSOR), AVG(TOTAL_ALUNOS), SUM(TOTAL_ALUNOS)
        INTO V_TOT_PROF, V_AVG_ALUNO, V_TOT_ALUNO FROM PROFESSOR P 
        WHERE P.ID_CIDADE = P_ID_CIDADE;
    DBMS_OUTPUT.PUT_LINE('NOME CIDADE: ' || V_NOME_CIDADE);
    DBMS_OUTPUT.PUT_LINE('NUMERO DE PROFESSORES QUE MORAM NA CIDADE: ' || V_TOT_PROF);
    DBMS_OUTPUT.PUT_LINE('MEDIA DE ALUNOS POR PROFESSORES: ' || V_AVG_ALUNO);
    DBMS_OUTPUT.PUT_LINE('TOTAL DE ALUNOS POR PROFESSORES: ' || V_TOT_ALUNO);       
END;

